FROM ros:foxy

# install packages
RUN apt-get update && apt-get install -q -y --no-install-recommends \
    python3-pip \
    flake8 \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install \
    autopep8 \
    black \
    yapf \
    bandit \
    mypy \
    pycodestyle==2.6.0 \
    pylint

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]